---
- name: Add PHP Repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Install PHP and PHP-FPM
  apt:
    pkg: [ 'php8.3-fpm','php8.3-cli','php8.3-mysql','php8.3-sqlite3','php8.3-curl','php8.3-gd','php8.3-intl','php8.3-imap','php8.3-ldap','php8.3-mbstring','php8.3-xml','php8.3-zip','php8.3-bz2','php8.3-imagick','php8.3-bcmath','php8.3-soap','php8.3-readline','php-memcached','php-msgpack','php-igbinary', 'php-redis' ]
    state: present
    update_cache: true

- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

- name: Make Composer Executable
  shell: chmod a+x /usr/local/bin/composer

- name: Composer Self Update
  shell: composer self-update

- name: Add PHP-FPM PHP Configuration
  copy:
    src: php.ini
    dest: /etc/php/8.3/fpm/php.ini
    owner: root
    group: root

- name: Add PHP-FPM Pool Configuration
  copy:
    src: www.conf
    dest: /etc/php/8.3/fpm/pool.d/www.conf
    owner: root
    group: root

- name: Restart PHP-FPM
  service:
    name: php8.3-fpm
    state: restarted